version: '2'

services:
   backend:
      image: tuanpt9898/backend-app:1.0
      restart: always
      ports:
        - "8000:8000"
      environment:
        FRONT_URL: http://${IP_HOST}:5000
   frontend:
      depends_on:
        - backend
      image: tuanpt9898/frontend-app:1.0
      restart: always
      ports:
        - "5000:5000"
      environment:
        API_URL: http://${IP_HOST}:8000
      
